// Mock data + state machine
const CHECKLIST_REQUIRED = [
  "Certificate of Registration of Business valid and uploaded",
  "Ministry of Works and Housing Certificate valid and uploaded",
  "Current Tax Clearance Certificate valid and uploaded",
  "SSNIT Clearance Certificate valid and uploaded",
  "Organisation Structure submitted",
  "PPA Registration submitted",
  "Bank Statement submitted",
  "Office location confirmed with working phone/email",
  "At least one Civil Engineer or Technician Engineer on permanent staff",
  "At least one certified Pipe Fitter on permanent staff",
];
const CHECKLIST_OPTIONAL = [
  "Owns at least one vehicle (pickup / truck / low loader) with ownership proof",
  "Owns heavy construction equipment with serial numbers and ownership proof",
  "Owns pipe testing equipment",
  "Has 3+ previous similar projects with proof of execution",
  "Has 5+ previous similar projects with proof of execution",
  "Has 3+ permanent pipe fitters",
  "Has dedicated warehouse with facilities description",
  "Has documented line of credit or strong bank position",
];
const MANDATORY_DOCS = [
  "Cert of Registration of Business",
  "Min of Works & Housing Cert",
  "Current Tax Clearance Cert",
  "SSNIT Clearance Cert",
  "Organisation Structure",
  "PPA Registration",
];

const calcGrade = (required, optional) => {
  if (required < 10) return null;
  if (optional >= 7) return "A";
  if (optional >= 4) return "B";
  if (optional >= 2) return "C";
  return "D";
};

const today = new Date();
const iso = (d) => d.toISOString();
const addDays = (d, n) => { const x = new Date(d); x.setDate(x.getDate() + n); return x; };

// Build initial dataset — 7 apps across states
const SEED_APPS = [
  {
    id: "APP-2026-0018",
    company: "Accra Plumbing Works Ltd",
    md: "Kwame Boateng",
    email: "info@accraplumbing.com.gh",
    phone: "+233 30 277 4421",
    fax: "+233 30 277 4422",
    postal: "P.O. Box AN 4421, Accra-North",
    office: "12 Farrar Avenue, Adabraka, Accra",
    officeManned: "Yes",
    warehouse: "North Industrial Area, near Achimota",
    warehouseDesc: "600 sqm covered storage, pipe rack system, loading bay, office",
    licenceType: "Plumbing Contractor",
    appType: "New",
    status: "DRAFT",
    fee: 250,
    submittedDate: null,
    submittedBy: "data.capture@gwcl",
    token: null,
    regNo: null,
    registrationDate: null,
    expiryDate: null,
    grade: null,
    checklistRequired: [],
    checklistOptional: [],
    docs: { "Cert of Registration of Business": { name: "ACCRA-cert-reg.pdf" }, "Min of Works & Housing Cert": { name: "ACCRA-mwh.pdf" } },
    staff: [
      { name: "Kwame Boateng", role: "Civil Engineer", qual: "BSc Civil, KNUST 2011", years: 14, file: "kwame-cv.pdf" },
      { name: "Abena Osei", role: "Pipe Fitter", qual: "Certified, NVTI", years: 8, file: "abena-cert.pdf" },
    ],
    tools: [
      { category: "Pickup", type: "Toyota Hilux 2019", serial: "HLX-4429-AC", dom: "2019-03-01", file: "hilux-reg.pdf" },
    ],
    projects: [
      { name: "Madina Community Water Line", details: "2.1km, 110mm HDPE", cost: 186000, year: 2023, file: "madina-proof.pdf" },
    ],
    financial: { bank: "Ecobank Ghana", statement: "ecobank-stmt.pdf", credit: null },
    audit: [
      { action: "Created", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -3)), notes: "Draft created" },
      { action: "Edited", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -2)), notes: "Added staff & tools" },
    ],
  },
  {
    id: "APP-2026-0017",
    company: "Takoradi Waterworks Co.",
    md: "Akosua Nyarko",
    email: "admin@takoradiwaterworks.gh",
    phone: "+233 31 202 3311",
    fax: "",
    postal: "P.O. Box 221, Takoradi",
    office: "Plot 17 Harbour Road, Takoradi",
    officeManned: "Yes",
    warehouse: "Effia-Kuma yard, Takoradi",
    warehouseDesc: "Open yard 400 sqm with secure fencing, covered shed",
    licenceType: "Master Plumber",
    appType: "New",
    status: "PENDING_APPROVAL",
    fee: 250,
    submittedDate: iso(addDays(today, -5)),
    submittedBy: "Adjoa Mensah (Admin)",
    token: null,
    regNo: null,
    registrationDate: null,
    expiryDate: null,
    grade: null,
    checklistRequired: [],
    checklistOptional: [],
    docs: Object.fromEntries(MANDATORY_DOCS.map(d => [d, { name: `TKD-${d.slice(0,8).replace(/ /g,"_")}.pdf` }])),
    staff: [
      { name: "Kojo Appiah", role: "Technician Engineer", qual: "HND Building & Civil, Takoradi Poly 2015", years: 9, file: "kojo-cv.pdf" },
      { name: "Yaw Asante", role: "Pipe Fitter", qual: "Certified, NVTI 2014", years: 11, file: "yaw-cert.pdf" },
      { name: "Esi Owusu", role: "Administrative Staff", qual: "BA Admin, UCC 2018", years: 6, file: "esi-cv.pdf" },
    ],
    tools: [
      { category: "Crane Truck", type: "Hino 500 Series", serial: "HN500-88-TK", dom: "2020-07-01", file: "hino-reg.pdf" },
      { category: "Pipe Testing Equipment", type: "Hydrostatic Test Pump 350bar", serial: "HTP-350-14", dom: "2021-02-01", file: "htp-inv.pdf" },
    ],
    projects: [
      { name: "Sekondi Harbour Pipe Rehab", details: "1.8km 200mm DI pipe replacement", cost: 450000, year: 2022, file: "sekondi-cert.pdf" },
      { name: "Ahanta West Borehole Mains", details: "5 boreholes, 3.2km network", cost: 312000, year: 2024, file: "ahanta-cert.pdf" },
    ],
    financial: { bank: "GCB Bank Ghana", statement: "gcb-stmt.pdf", credit: "gcb-credit.pdf" },
    audit: [
      { action: "Created", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -8)), notes: "" },
      { action: "Submitted", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -5)), notes: "Submitted for approval" },
    ],
  },
  {
    id: "APP-2026-0016",
    company: "Ashanti Pipeline Services Ltd",
    md: "Nana Yaw Addo",
    email: "ops@ashantipipeline.com",
    phone: "+233 32 202 7788",
    fax: "",
    postal: "P.O. Box KS 1029, Kumasi",
    office: "44 Lake Road, Adum, Kumasi",
    officeManned: "No",
    warehouse: "Suame Magazine",
    warehouseDesc: "Shared workshop space",
    licenceType: "Plumbing Contractor",
    appType: "New",
    status: "REJECTED",
    fee: 250,
    submittedDate: iso(addDays(today, -10)),
    submittedBy: "Adjoa Mensah (Admin)",
    reviewedBy: "Eng. K. Ofori (Super Admin)",
    reviewedDate: iso(addDays(today, -7)),
    rejectionReason: "Tax Clearance Certificate has expired (valid only until Dec 2025). SSNIT clearance missing stamp. Please update and resubmit.",
    docs: Object.fromEntries(MANDATORY_DOCS.slice(0,5).map(d => [d, { name: `ASH-${d.slice(0,8)}.pdf` }])),
    staff: [{ name: "Nana Yaw Addo", role: "Civil Engineer", qual: "BSc Civil", years: 5, file: "nana-cv.pdf" }],
    tools: [],
    projects: [],
    financial: { bank: "Zenith Bank Ghana", statement: "zenith-stmt.pdf", credit: null },
    grade: null, checklistRequired: [], checklistOptional: [],
    audit: [
      { action: "Created", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -12)), notes: "" },
      { action: "Submitted", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -10)), notes: "" },
      { action: "Rejected", by: "Eng. K. Ofori (Super Admin)", ts: iso(addDays(today, -7)), notes: "See rejection reason" },
    ],
  },
  {
    id: "APP-2026-0015",
    company: "Tamale Pipe Services",
    md: "Mohammed Abubakari",
    email: "tamalepipe@gmail.com",
    phone: "+233 37 202 1144",
    fax: "",
    postal: "P.O. Box TL 318, Tamale",
    office: "Education Ridge, Tamale",
    officeManned: "Yes",
    warehouse: "Lamashegu Industrial Lot",
    warehouseDesc: "Walled compound 300 sqm, metal shed 120 sqm",
    licenceType: "Plumbing Contractor",
    appType: "New",
    status: "TOKEN_ISSUED",
    fee: 250,
    submittedDate: iso(addDays(today, -12)),
    submittedBy: "Adjoa Mensah (Admin)",
    reviewedBy: "Eng. K. Ofori (Super Admin)",
    reviewedDate: iso(addDays(today, -6)),
    approvalComments: "Strong documentation. Proceed to payment.",
    token: "GWCL-2026-TPS-308244",
    tokenIssuedDate: iso(addDays(today, -6)),
    tokenExpiryDate: iso(addDays(today, 24)),
    docs: Object.fromEntries(MANDATORY_DOCS.map(d => [d, { name: `TML-${d.slice(0,8).replace(/ /g,"_")}.pdf` }])),
    staff: [
      { name: "Mohammed Abubakari", role: "Civil Engineer", qual: "BSc Civil, UDS 2012", years: 12, file: "mohammed-cv.pdf" },
      { name: "Fatima Issah", role: "Pipe Fitter", qual: "NVTI Certificate", years: 7, file: "fatima-cert.pdf" },
    ],
    tools: [
      { category: "Pickup", type: "Nissan Navara", serial: "NVR-2201-TL", dom: "2021-05-01", file: "navara.pdf" },
      { category: "Ordinary Truck", type: "Mitsubishi Canter 4t", serial: "MTS-0088-TL", dom: "2020-08-01", file: "canter.pdf" },
    ],
    projects: [
      { name: "Nyankpala Campus Waterline", details: "800m 63mm HDPE", cost: 72000, year: 2023, file: "nyank.pdf" },
    ],
    financial: { bank: "Agricultural Development Bank", statement: "adb-stmt.pdf", credit: null },
    grade: null, checklistRequired: [], checklistOptional: [],
    audit: [
      { action: "Created", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -14)), notes: "" },
      { action: "Submitted", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -12)), notes: "" },
      { action: "Approved", by: "Eng. K. Ofori (Super Admin)", ts: iso(addDays(today, -6)), notes: "Proceed to payment" },
      { action: "Token Issued", by: "System", ts: iso(addDays(today, -6)), notes: "GWCL-2026-TPS-308244" },
    ],
  },
  {
    id: "APP-2026-0014",
    company: "Volta Rivers Plumbing Ltd",
    md: "Selorm Agbo",
    email: "selorm@voltariversplb.com",
    phone: "+233 36 202 4455",
    fax: "+233 36 202 4456",
    postal: "P.O. Box HO 102, Ho",
    office: "Industrial Estate Rd, Ho",
    officeManned: "Yes",
    warehouse: "Ho Sokode yard",
    warehouseDesc: "Concrete yard 500 sqm, workshop 180 sqm, admin block",
    licenceType: "Master Plumber",
    appType: "New",
    status: "PENDING_FINAL_APPROVAL",
    fee: 250,
    submittedDate: iso(addDays(today, -18)),
    reviewedBy: "Eng. K. Ofori (Super Admin)",
    reviewedDate: iso(addDays(today, -11)),
    submittedBy: "Adjoa Mensah (Admin)",
    token: "GWCL-2026-VRP-611902",
    tokenIssuedDate: iso(addDays(today, -11)),
    tokenExpiryDate: iso(addDays(today, 19)),
    receiptNumber: "R7-2026-04-3311",
    paymentDate: iso(addDays(today, -3)),
    paymentRecordedBy: "Adjoa Mensah (Admin)",
    receiptFile: "volta-receipt.pdf",
    docs: Object.fromEntries(MANDATORY_DOCS.map(d => [d, { name: `VOL-${d.slice(0,8).replace(/ /g,"_")}.pdf` }])),
    staff: [
      { name: "Selorm Agbo", role: "Civil Engineer", qual: "BSc + MSc Civil, KNUST", years: 18, file: "selorm-cv.pdf" },
      { name: "Dela Kuma", role: "Technician Engineer", qual: "HND Building, Ho Polytechnic", years: 10, file: "dela-cv.pdf" },
      { name: "Kofi Ametame", role: "Pipe Fitter", qual: "NVTI Certified", years: 15, file: "kofi-cert.pdf" },
      { name: "Afi Dziedzorm", role: "Pipe Fitter", qual: "NVTI Certified", years: 8, file: "afi-cert.pdf" },
      { name: "Paul Klu", role: "Pipe Fitter", qual: "NVTI Certified", years: 12, file: "paul-cert.pdf" },
    ],
    tools: [
      { category: "Crane Truck", type: "Isuzu Giga 14t with crane", serial: "ISG-1104-VR", dom: "2019-06-01", file: "isuzu.pdf" },
      { category: "Low Loader", type: "Mercedes Actros Low Loader", serial: "MAL-7702-VR", dom: "2020-04-01", file: "mercedes.pdf" },
      { category: "Pipe Testing Equipment", type: "Pressure Test Rig 420bar", serial: "PTR-420-VR", dom: "2022-01-01", file: "ptr.pdf" },
      { category: "Heavy Construction Equipment", type: "JCB 3CX Backhoe Loader", serial: "JCB-3CX-VR", dom: "2018-11-01", file: "jcb.pdf" },
    ],
    projects: [
      { name: "Ho Township Trunk Main", details: "4.2km 300mm DI", cost: 1200000, year: 2022, file: "ho-trunk.pdf" },
      { name: "Kpando District Supply", details: "2.8km 200mm PVC", cost: 680000, year: 2023, file: "kpando.pdf" },
      { name: "Aflao Border Supply", details: "1.4km 150mm HDPE", cost: 410000, year: 2024, file: "aflao.pdf" },
      { name: "Keta Coastal Protection Pipeline", details: "Storm pipeline, 900m", cost: 280000, year: 2023, file: "keta.pdf" },
    ],
    financial: { bank: "Fidelity Bank Ghana", statement: "fidelity-stmt.pdf", credit: "fidelity-loc.pdf" },
    grade: null, checklistRequired: [], checklistOptional: [],
    audit: [
      { action: "Created", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -20)), notes: "" },
      { action: "Submitted", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -18)), notes: "" },
      { action: "Approved", by: "Eng. K. Ofori (Super Admin)", ts: iso(addDays(today, -11)), notes: "Well-documented, proceed" },
      { action: "Token Issued", by: "System", ts: iso(addDays(today, -11)), notes: "GWCL-2026-VRP-611902" },
      { action: "Payment Recorded", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -3)), notes: "Receipt R7-2026-04-3311 uploaded" },
    ],
  },
  {
    id: "APP-2025-0112",
    company: "Cape Coast Hydraulics Ltd",
    md: "Efua Annan",
    email: "hq@capecoasthydraulics.gh",
    phone: "+233 33 213 5501",
    fax: "",
    postal: "P.O. Box CC 219, Cape Coast",
    office: "University Rd, Cape Coast",
    officeManned: "Yes",
    warehouse: "Abura industrial zone",
    warehouseDesc: "Covered workshop 350 sqm",
    licenceType: "Plumbing Contractor",
    appType: "New",
    status: "REGISTERED",
    fee: 250,
    submittedDate: iso(addDays(today, -80)),
    submittedBy: "Adjoa Mensah (Admin)",
    reviewedBy: "Eng. K. Ofori (Super Admin)",
    reviewedDate: iso(addDays(today, -72)),
    token: "GWCL-2025-CCH-882013",
    tokenIssuedDate: iso(addDays(today, -72)),
    tokenExpiryDate: iso(addDays(today, -42)),
    receiptNumber: "R7-2025-10-0921",
    paymentDate: iso(addDays(today, -65)),
    paymentRecordedBy: "Adjoa Mensah (Admin)",
    paymentVerifiedBy: "Eng. K. Ofori (Super Admin)",
    paymentVerifiedDate: iso(addDays(today, -62)),
    receiptFile: "cch-receipt.pdf",
    regNo: "GWCL/PLB/2025/0112",
    registrationDate: iso(addDays(today, -320)),
    expiryDate: iso(addDays(today, 45)),
    registeredBy: "Eng. K. Ofori (Super Admin)",
    grade: "B",
    checklistRequired: Array(10).fill(true).map((_,i) => i),
    checklistOptional: [0, 3, 5, 7],
    docs: Object.fromEntries(MANDATORY_DOCS.map(d => [d, { name: `CCH-${d.slice(0,8).replace(/ /g,"_")}.pdf` }])),
    staff: [
      { name: "Efua Annan", role: "Civil Engineer", qual: "BSc Civil, UCC 2010", years: 15, file: "efua-cv.pdf" },
      { name: "Joseph Mensah", role: "Pipe Fitter", qual: "NVTI", years: 9, file: "joseph-cert.pdf" },
      { name: "Mary Adu", role: "Pipe Fitter", qual: "NVTI", years: 6, file: "mary-cert.pdf" },
      { name: "Samuel Kwesi", role: "Pipe Fitter", qual: "NVTI", years: 10, file: "sam-cert.pdf" },
    ],
    tools: [
      { category: "Pickup", type: "Ford Ranger", serial: "FR-2210-CC", dom: "2020-06-01", file: "" },
      { category: "Ordinary Truck", type: "Hino 300", serial: "HN300-CC", dom: "2019-11-01", file: "" },
    ],
    projects: [
      { name: "Elmina Coastal Line", details: "1.2km 110mm", cost: 220000, year: 2022, file: "" },
      { name: "Mankessim District Pipe", details: "2km 160mm", cost: 410000, year: 2023, file: "" },
      { name: "Saltpond Mains Rehab", details: "1.8km 150mm", cost: 355000, year: 2024, file: "" },
    ],
    financial: { bank: "Stanbic Bank Ghana", statement: "stanbic-stmt.pdf", credit: "stanbic-loc.pdf" },
    audit: [
      { action: "Created", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -82)), notes: "" },
      { action: "Submitted", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -80)), notes: "" },
      { action: "Approved", by: "Eng. K. Ofori (Super Admin)", ts: iso(addDays(today, -72)), notes: "" },
      { action: "Token Issued", by: "System", ts: iso(addDays(today, -72)), notes: "GWCL-2025-CCH-882013" },
      { action: "Payment Recorded", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -65)), notes: "R7-2025-10-0921" },
      { action: "Payment Verified", by: "Eng. K. Ofori (Super Admin)", ts: iso(addDays(today, -62)), notes: "" },
      { action: "Registered", by: "Eng. K. Ofori (Super Admin)", ts: iso(addDays(today, -320)), notes: "Grade B issued" },
    ],
  },
  {
    id: "APP-2025-0089",
    company: "Greater Accra Waterworks Ltd",
    md: "Kwabena Sarpong",
    email: "admin@gawworks.gh",
    phone: "+233 30 277 9911",
    fax: "+233 30 277 9912",
    postal: "P.O. Box AN 9911, Accra",
    office: "Kwame Nkrumah Ave, Accra",
    officeManned: "Yes",
    warehouse: "Spintex Rd warehouse",
    warehouseDesc: "1200 sqm enclosed, 2 loading docks, admin annex",
    licenceType: "Master Plumber",
    appType: "New",
    status: "REGISTERED",
    fee: 250,
    submittedBy: "Adjoa Mensah (Admin)",
    reviewedBy: "Eng. K. Ofori (Super Admin)",
    submittedDate: iso(addDays(today, -480)),
    reviewedDate: iso(addDays(today, -470)),
    token: "GWCL-2024-GAW-199283",
    tokenIssuedDate: iso(addDays(today, -470)),
    tokenExpiryDate: iso(addDays(today, -440)),
    receiptNumber: "R7-2024-12-8812",
    paymentDate: iso(addDays(today, -462)),
    paymentRecordedBy: "Adjoa Mensah (Admin)",
    paymentVerifiedBy: "Eng. K. Ofori (Super Admin)",
    paymentVerifiedDate: iso(addDays(today, -455)),
    receiptFile: "gaw-receipt.pdf",
    regNo: "GWCL/PLB/2025/0089",
    registrationDate: iso(addDays(today, -210)),
    expiryDate: iso(addDays(today, 155)),
    registeredBy: "Eng. K. Ofori (Super Admin)",
    grade: "A",
    checklistRequired: Array(10).fill(true).map((_,i) => i),
    checklistOptional: [0, 1, 2, 3, 4, 5, 6, 7],
    docs: Object.fromEntries(MANDATORY_DOCS.map(d => [d, { name: `GAW-${d.slice(0,8).replace(/ /g,"_")}.pdf` }])),
    staff: [
      { name: "Kwabena Sarpong", role: "Civil Engineer", qual: "BSc Civil, KNUST + MBA", years: 22, file: "" },
      { name: "Hannah Nkrumah", role: "Technician Engineer", qual: "HND Building", years: 14, file: "" },
      { name: "George Adjei", role: "Pipe Fitter", qual: "NVTI Advanced", years: 18, file: "" },
      { name: "Nana Akua", role: "Pipe Fitter", qual: "NVTI", years: 11, file: "" },
      { name: "Michael Osei", role: "Pipe Fitter", qual: "NVTI", years: 9, file: "" },
    ],
    tools: [
      { category: "Crane Truck", type: "Mercedes Actros w/ HIAB", serial: "MA-HIAB-GAW", dom: "2018-05-01", file: "" },
      { category: "Low Loader", type: "Volvo FH Low Loader", serial: "VLV-LL-GAW", dom: "2019-10-01", file: "" },
      { category: "Heavy Construction Equipment", type: "CAT 320 Excavator", serial: "CAT-320-GAW", dom: "2017-04-01", file: "" },
      { category: "Pipe Testing Equipment", type: "Advanced Leak Test System", serial: "ALT-GAW", dom: "2022-06-01", file: "" },
    ],
    projects: [
      { name: "Tema Ring Main Upgrade", details: "6km 400mm DI", cost: 2800000, year: 2022, file: "" },
      { name: "Kasoa District Main", details: "4km 300mm DI", cost: 1650000, year: 2023, file: "" },
      { name: "Dodowa Township Network", details: "8km mixed 150-250mm", cost: 3200000, year: 2024, file: "" },
      { name: "Ga East Storage Facility", details: "500m³ reservoir + feeder main", cost: 890000, year: 2023, file: "" },
      { name: "Accra Central CBD Rehab", details: "2.2km trunk main", cost: 1450000, year: 2024, file: "" },
    ],
    financial: { bank: "Standard Chartered Ghana", statement: "scb-stmt.pdf", credit: "scb-loc-1.2M.pdf" },
    audit: [
      { action: "Created", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -485)), notes: "" },
      { action: "Submitted", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -480)), notes: "" },
      { action: "Approved", by: "Eng. K. Ofori (Super Admin)", ts: iso(addDays(today, -470)), notes: "" },
      { action: "Token Issued", by: "System", ts: iso(addDays(today, -470)), notes: "" },
      { action: "Payment Recorded", by: "Adjoa Mensah (Admin)", ts: iso(addDays(today, -462)), notes: "" },
      { action: "Payment Verified", by: "Eng. K. Ofori (Super Admin)", ts: iso(addDays(today, -455)), notes: "" },
      { action: "Registered", by: "Eng. K. Ofori (Super Admin)", ts: iso(addDays(today, -210)), notes: "Grade A — top-tier contractor" },
    ],
  },
];

// Earlier historical registered records (for analytics)
const HISTORICAL_EXTRA = [
  { grade: "A", fee: 250, appType: "New", registrationDate: iso(addDays(today, -340)) },
  { grade: "B", fee: 250, appType: "New", registrationDate: iso(addDays(today, -300)) },
  { grade: "B", fee: 150, appType: "Renewal", registrationDate: iso(addDays(today, -260)) },
  { grade: "C", fee: 250, appType: "New", registrationDate: iso(addDays(today, -220)) },
  { grade: "A", fee: 150, appType: "Renewal", registrationDate: iso(addDays(today, -180)) },
  { grade: "B", fee: 250, appType: "New", registrationDate: iso(addDays(today, -150)) },
  { grade: "D", fee: 250, appType: "New", registrationDate: iso(addDays(today, -120)) },
  { grade: "B", fee: 150, appType: "Renewal", registrationDate: iso(addDays(today, -90)) },
  { grade: "C", fee: 150, appType: "Renewal", registrationDate: iso(addDays(today, -60)) },
  { grade: "A", fee: 250, appType: "New", registrationDate: iso(addDays(today, -30)) },
];

// Computed helper: derive "expiring soon" transition automatically
const deriveStatus = (app) => {
  if (app.status !== "REGISTERED" && app.status !== "EXPIRING_SOON" && app.status !== "EXPIRED" && app.status !== "LAPSED") return app.status;
  if (!app.expiryDate) return app.status;
  const dte = daysToExpiry(app.expiryDate);
  if (dte < -30) return "LAPSED";
  if (dte < 0) return "EXPIRED";
  if (dte <= 60) return "EXPIRING_SOON";
  return "REGISTERED";
};

Object.assign(window, {
  CHECKLIST_REQUIRED, CHECKLIST_OPTIONAL, MANDATORY_DOCS,
  SEED_APPS, HISTORICAL_EXTRA, calcGrade, deriveStatus,
});
